[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "seguimiento-medios"
version = "0.1.0"
description = "Pipeline de scraping + ASR + chatbot para análisis de sentimiento por términos"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
]

[project.scripts]
start-server = "api:run"
run-pipeline = "pipeline.ejecucion:run"

[tool.setuptools.packages.find]
where = ["src"]  # Busca todo dentro de src
include = ["*"]  # Incluye todos los subpaquetes automáticamente